### ISSUE TITLE
Switch to a better toolkit

### ISSUE THREAD

**Issue by tophf** [openstyles/stylelint-bundle#10]
The problem with browserify is that it uses insert-module-globals which always wraps modules into an additional IIFE + call. It also doesn't seem to have a straightforward method of applying our transforms on-the-fly to child packages, meaning that we have to patch stylelint on the disk, and that is wasteful, slow, and just wrong.

I guess we'll try rollup.

* Add stylelint as a dependency in package.json.
* Apply transforms on-the-fly.
* Rewrite some patches to use dummy modules where possible and reasonable, but keep regexp if there's a noticeable size reduction, say at least half a kb.
* Keep the check to ensure each replacement actually occurred, and call process.exit(1) otherwise.

**Comment by Mottie** [comment]
I tried rollup. wow 5 years ago, but I couldn't get it to work - see https://github.com/Mottie/stylelint-bundler

I hope things have changed since then.
